/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminAddProductRouteImport } from './routes/admin-add-product'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as SoftwareIdRouteImport } from './routes/software.$id'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as HardwareIdRouteImport } from './routes/hardware.$id'

const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddProductRoute = AdminAddProductRouteImport.update({
  id: '/admin-add-product',
  path: '/admin-add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const SoftwareIdRoute = SoftwareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SoftwareRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const HardwareIdRoute = HardwareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HardwareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-add-product': typeof AdminAddProductRoute
  '/contact': typeof ContactRoute
  '/hardware': typeof HardwareRouteWithChildren
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRouteWithChildren
  '/software': typeof SoftwareRouteWithChildren
  '/hardware/$id': typeof HardwareIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/software/$id': typeof SoftwareIdRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-add-product': typeof AdminAddProductRoute
  '/contact': typeof ContactRoute
  '/hardware': typeof HardwareRouteWithChildren
  '/products': typeof ProductsRoute
  '/software': typeof SoftwareRouteWithChildren
  '/hardware/$id': typeof HardwareIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/software/$id': typeof SoftwareIdRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-add-product': typeof AdminAddProductRoute
  '/contact': typeof ContactRoute
  '/hardware': typeof HardwareRouteWithChildren
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRouteWithChildren
  '/software': typeof SoftwareRouteWithChildren
  '/hardware/$id': typeof HardwareIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/software/$id': typeof SoftwareIdRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-add-product'
    | '/contact'
    | '/hardware'
    | '/products'
    | '/services'
    | '/software'
    | '/hardware/$id'
    | '/services/$slug'
    | '/software/$id'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-add-product'
    | '/contact'
    | '/hardware'
    | '/products'
    | '/software'
    | '/hardware/$id'
    | '/services/$slug'
    | '/software/$id'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-add-product'
    | '/contact'
    | '/hardware'
    | '/products'
    | '/services'
    | '/software'
    | '/hardware/$id'
    | '/services/$slug'
    | '/software/$id'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminAddProductRoute: typeof AdminAddProductRoute
  ContactRoute: typeof ContactRoute
  HardwareRoute: typeof HardwareRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SoftwareRoute: typeof SoftwareRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-add-product': {
      id: '/admin-add-product'
      path: '/admin-add-product'
      fullPath: '/admin-add-product'
      preLoaderRoute: typeof AdminAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/software/$id': {
      id: '/software/$id'
      path: '/$id'
      fullPath: '/software/$id'
      preLoaderRoute: typeof SoftwareIdRouteImport
      parentRoute: typeof SoftwareRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/hardware/$id': {
      id: '/hardware/$id'
      path: '/$id'
      fullPath: '/hardware/$id'
      preLoaderRoute: typeof HardwareIdRouteImport
      parentRoute: typeof HardwareRoute
    }
  }
}

interface HardwareRouteChildren {
  HardwareIdRoute: typeof HardwareIdRoute
}

const HardwareRouteChildren: HardwareRouteChildren = {
  HardwareIdRoute: HardwareIdRoute,
}

const HardwareRouteWithChildren = HardwareRoute._addFileChildren(
  HardwareRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SoftwareRouteChildren {
  SoftwareIdRoute: typeof SoftwareIdRoute
}

const SoftwareRouteChildren: SoftwareRouteChildren = {
  SoftwareIdRoute: SoftwareIdRoute,
}

const SoftwareRouteWithChildren = SoftwareRoute._addFileChildren(
  SoftwareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminAddProductRoute: AdminAddProductRoute,
  ContactRoute: ContactRoute,
  HardwareRoute: HardwareRouteWithChildren,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SoftwareRoute: SoftwareRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
