/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as SoftwareRouteImport } from './routes/software';
import { Route as ServicesRouteImport } from './routes/services';
import { Route as ProductsRouteImport } from './routes/products';
import { Route as HardwareRouteImport } from './routes/hardware';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as AdminAddProductRouteImport } from './routes/admin-add-product';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ServicesIndexRouteImport } from './routes/services.index';
import { Route as SoftwareIdRouteImport } from './routes/software.$id';
import { Route as ServicesSlugRouteImport } from './routes/services.$slug';
import { Route as HardwareIdRouteImport } from './routes/hardware.$id';
const SoftwareRoute = SoftwareRouteImport.update({
    id: '/software',
    path: '/software',
    getParentRoute: () => rootRouteImport,
});
const ServicesRoute = ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => rootRouteImport,
});
const ProductsRoute = ProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => rootRouteImport,
});
const HardwareRoute = HardwareRouteImport.update({
    id: '/hardware',
    path: '/hardware',
    getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => rootRouteImport,
});
const AdminAddProductRoute = AdminAddProductRouteImport.update({
    id: '/admin-add-product',
    path: '/admin-add-product',
    getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const ServicesIndexRoute = ServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServicesRoute,
});
const SoftwareIdRoute = SoftwareIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => SoftwareRoute,
});
const ServicesSlugRoute = ServicesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ServicesRoute,
});
const HardwareIdRoute = HardwareIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => HardwareRoute,
});
const HardwareRouteChildren = {
    HardwareIdRoute: HardwareIdRoute,
};
const HardwareRouteWithChildren = HardwareRoute._addFileChildren(HardwareRouteChildren);
const ServicesRouteChildren = {
    ServicesSlugRoute: ServicesSlugRoute,
    ServicesIndexRoute: ServicesIndexRoute,
};
const ServicesRouteWithChildren = ServicesRoute._addFileChildren(ServicesRouteChildren);
const SoftwareRouteChildren = {
    SoftwareIdRoute: SoftwareIdRoute,
};
const SoftwareRouteWithChildren = SoftwareRoute._addFileChildren(SoftwareRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    AdminRoute: AdminRoute,
    AdminAddProductRoute: AdminAddProductRoute,
    ContactRoute: ContactRoute,
    HardwareRoute: HardwareRouteWithChildren,
    ProductsRoute: ProductsRoute,
    ServicesRoute: ServicesRouteWithChildren,
    SoftwareRoute: SoftwareRouteWithChildren,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
